---
apiVersion: v1
kind: Service
metadata:
  name: service-dns
  namespace: service-test
  labels:
    service: net
  annotations:
    lbipam.cilium.io/sharing-key: service
    lbipam.cilium.io/ips: 20.0.10.1
spec:
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
