---
apiVersion: v1
kind: Service
metadata:
  name: service-dhcp
  namespace: service-test
  labels:
    service: net
  annotations:
    lbipam.cilium.io/sharing-key: service
spec:
  type: LoadBalancer
  loadBalancerIP: 20.0.10.1
  ports:
  - port: 67
    protocol: UDP
